[package]
name = "gamus-fs"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["fs", "macros", "rt-multi-thread"] }
