[package]
name = "gamus-metadata"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1.89"
gamus-core = { version = "0.1.0", path = "../gamus-core" }
tokio = "1.48.0"
